SELECT DEPARTMENT_NAME "학과 명",CATEGORY "계열"
FROM tb_department;

SELECT DEPARTMENT_NAME || '의 정원은'||CAPACITY||'명 입니다.' AS "학과별 정원"
FROM tb_department;

SELECT STUDENT_NAME,department_name FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE absence_yn = 'Y'
AND SUBSTR(STUDENT_SSN,8,1)=2
AND department_name = '국어국문학과';

SELECT STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NO IN ( 'A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NO DESC;


SELECT DEPARTMENT_NAME,CATEGORY FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT PROFESSOR_NAME FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
AND STUDENT_NO LIKE 'A2%'
AND STUDENT_ADDRESS LIKE '%전주%'
ORDER BY STUDENT_NAME;

-------------------------------------------------------------------------------------
--1
SELECT STUDENT_NO 학번,STUDENT_NAME 이름,ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO =02 
ORDER BY ENTRANCE_DATE;

--2
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3
--SELECT PROFESSOR_NAME 교수이름 ,PROFESSOR_SSN 나이 
--FROM TB_PROFESSOR
--WHERE(SYSDATE-PROFESSOR_SSN+1);

       --ORA-01843: 지정한 월이 부적합합니다. '19'||안쓰면 오류 발생(주민등록상의 950103이라고 쓰여있어서 YY가 형태가 없다. YYYYMMDD)

SELECT PROFESSOR_NAME"교수이름"
FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19||SUBSTR(PROFESSOR_SSN,1,6),'YYYYMMDD'))//12)"나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)=1
ORDER BY "나이";

--4
SELECT SUBSTR(PROFESSOR_NAME,2,2) 이름 
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
    -  EXTRACT(YEAR FROM  TO_DATE('19'||SUBSTR(STUDENT_SSN,1,6),'YYYYMMDD'))>19;
--WHERE SUBSTR(ENTRANCE_DATE,1,2) - SUBSTR(STUDENT_SSN,1,2) >=19;

--6
SELECT TO_CHAR((TO_DATE(20201225)), 'day')FROM DUAL;

--7
SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL; 
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL; 
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL; 

--8
SELECT STUDENT_NO,STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

--12
SELECT SUBSTR(TERM_NO,1,4) AS "년도",ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO='A112113'
GROUP BY  SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13                                         COUNT(함수식) - 함수의 결과가 있을떄 (NULL이 아닐때 카운트)-없는 칼럼을 만든다.        
SELECT DEPARTMENT_NO,COUNT(DECODE(ABSENCE_YN,'Y','Y','N0',0)) "휴학생 수 "
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT DEPARTMENT_NO,SUM(DECODE(ABSENCE_YN,'Y',1,0)) "휴학생 수 "
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14
SELECT STUDENT_NAME 동일이름,COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY 1;


--15

